name: kaportapp
description: >-
  KaportApp, kaporta atölyeleri için geliştirilen; araç kabul süreçlerini,
  çoklu parça siparişlerini ve ekip görev takibini tek ekranda toplayan bir
  iç işleyiş uygulamasıdır.
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.24.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.10
  firebase_core_platform_interface: ^6.0.2

flutter:
  uses-material-design: true
