name: kaportapp
description: >-
  KaportApp, kaporta atölyeleri için geliştirilen; araç kabul süreçlerini,
  çoklu parça siparişlerini ve ekip görev takibini tek ekranda toplayan bir
  iç işleyiş uygulamasıdır.
publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.24.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  path_provider: ^2.1.3
  pdf: ^3.10.5
  printing: ^5.13.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.10
  firebase_core_platform_interface: ^6.0.2
  mocktail: ^1.0.3
  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
