// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxu0Gkh6tVzwENqpazepGU5IHtGPjuZpk',
    appId: '1:176601747513:web:e1fc6813cd00ae61a27de8',
    messagingSenderId: '176601747513',
    projectId: 'kaportapp',
    authDomain: 'kaportapp.firebaseapp.com',
    storageBucket: 'kaportapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMbHfdNkTVyP9kSc7nPKyKHQ_8CLbs8A',
    appId: '1:176601747513:android:808b62ff863b9c15a27de8',
    messagingSenderId: '176601747513',
    projectId: 'kaportapp',
    storageBucket: 'kaportapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUUQ-HFseydAOTPpdn9XwXJYskqnFRp8U',
    appId: '1:176601747513:ios:0b0be11e97e4c7e4a27de8',
    messagingSenderId: '176601747513',
    projectId: 'kaportapp',
    storageBucket: 'kaportapp.firebasestorage.app',
    iosBundleId: 'com.splaxtr.kaportapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUUQ-HFseydAOTPpdn9XwXJYskqnFRp8U',
    appId: '1:176601747513:ios:0b0be11e97e4c7e4a27de8',
    messagingSenderId: '176601747513',
    projectId: 'kaportapp',
    storageBucket: 'kaportapp.firebasestorage.app',
    iosBundleId: 'com.splaxtr.kaportapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxu0Gkh6tVzwENqpazepGU5IHtGPjuZpk',
    appId: '1:176601747513:web:1fd2f64ca01ea854a27de8',
    messagingSenderId: '176601747513',
    projectId: 'kaportapp',
    authDomain: 'kaportapp.firebaseapp.com',
    storageBucket: 'kaportapp.firebasestorage.app',
  );
}
