name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

jobs:
  setup-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pub cache
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter (master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

  analyze-and-test:
    needs: setup-flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore pub cache
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter (master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter test with coverage
        run: flutter test --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

  build-web:
    needs: analyze-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore pub cache
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter (master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web (release)
        run: flutter build web --release

      - name: Upload web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: build/web

  build-apk:
    needs: analyze-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore pub cache
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Flutter (master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy-release:
    needs: [build-web, build-apk]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Download web artifact
        uses: actions/download-artifact@v3
        with:
          name: web-release
          path: web-release

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: android-apk

      - name: Attach assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web-release/**
            android-apk/app-release.apk
